# Generated by Django 2.0.6 on 2018-07-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('Id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('salary', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('imageUrl', models.CharField(max_length=30)),
                ('videoUrl', models.CharField(max_length=30)),
            ],
        ),
    ]
