# Generated by Django 2.0.6 on 2018-07-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='imageUrl',
            field=models.ImageField(blank=True, default='defoult.png', upload_to=''),
        ),
    ]
