# Generated by Django 2.0.6 on 2018-10-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_auto_20180710_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('Id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('birth_date', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='videoUrl',
            field=models.FileField(upload_to=''),
        ),
    ]
