# Generated by Django 2.0.6 on 2018-10-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_auto_20181004_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(max_length=30),
        ),
    ]
