# Generated by Django 2.0.6 on 2018-10-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0005_auto_20181004_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
