# Generated by Django 2.0.6 on 2018-10-08 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0007_dronauser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dronauser',
        ),
    ]
